const waves = Object.freeze({
  wave1: {
    waveName: 'Easy Going',
    waveEnemies: {
      0: {
        id: 0,
        x: 50,
        y: -50,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      1: {
        id: 1,
        x: 200,
        y: -50,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      2: {
        id: 2,
        x: 550,
        y: -100,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      3: {
        id: 3,
        x: 410,
        y: -150,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      4: {
        id: 4,
        x: 400,
        y: -200,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      5: {
        id: 5,
        x: 200,
        y: -250,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      6: {
        id: 6,
        x: 450,
        y: -300,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
    },
  },
  wave2: {
    waveName: 'Quick Ones',
    waveEnemies: {
      0: {
        id: 0,
        x: 50,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 6,
        hp: 1,
        damage: 1,

      },
      1: {
        id: 1,
        x: 400,
        y: -40,
        radius: 20,
        color: 'green',
        speed: 6,
        hp: 1,
        damage: 1,


      },
      2: {
        id: 2,
        x: 300,
        y: -120,
        radius: 20,
        color: 'green',
        speed: 6,
        hp: 1,
        damage: 1,

      },
    },
  },
  wave3: {
    waveName: 'Fresh Horde',
    waveEnemies: {
      0: {
        id: 0,
        x: 50,
        y: -12,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      1: {
        id: 1,
        x: 75,
        y: -42,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      2: {
        id: 2,
        x: 138,
        y: -87,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      3: {
        id: 3,
        x: 225,
        y: -137,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      4: {
        id: 4,
        x: 335,
        y: -54,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      5: {
        id: 5,
        x: 445,
        y: -274,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      6: {
        id: 6,
        x: 323,
        y: -466,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      7: {
        id: 7,
        x: 185,
        y: -123,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      8: {
        id: 8,
        x: 465,
        y: -78,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      9: {
        id: 9,
        x: 530,
        y: -99,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      10: {
        id: 10,
        x: 225,
        y: -43,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      11: {
        id: 11,
        x: 500,
        y: -12,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      12: {
        id: 12,
        x: 340,
        y: -31,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      13: {
        id: 13,
        x: 578,
        y: -65,
        radius: 30,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },


    },
  },
  wave4: {
    waveName: 'Slow Ones',
    waveEnemies: {
      0: {
        id: 0,
        x: 50,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      1: {
        id: 1,
        x: 100,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,


      },
      2: {
        id: 2,
        x: 150,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      3: {
        id: 3,
        x: 450,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      4: {
        id: 4,
        x: 500,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,


      },
      5: {
        id: 5,
        x: 550,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
    },
  },
  wave5: {
    waveName: 'Scrum',
    waveEnemies: {
      0: {
        id: 0,
        x: 50,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      1: {
        id: 1,
        x: 100,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,


      },
      2: {
        id: 2,
        x: 150,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      3: {
        id: 3,
        x: 200,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      4: {
        id: 4,
        x: 250,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      5: {
        id: 5,
        x: 300,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      6: {
        id: 6,
        x: 350,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      7: {
        id: 7,
        x: 400,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      8: {
        id: 8,
        x: 450,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      9: {
        id: 9,
        x: 500,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
      10: {
        id: 10,
        x: 550,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,
      },
    },
  },
  wave6: {
    waveName: 'Speed Demons',
    waveEnemies: {
      0: {
        id: 0,
        x: 150,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 4,
        hp: 1,
        damage: 1,

      },
      1: {
        id: 1,
        x: 250,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 4,
        hp: 1,
        damage: 1,


      },
      2: {
        id: 2,
        x: 350,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 4,
        hp: 1,
        damage: 1,

      },
      3: {
        id: 3,
        x: 450,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 4,
        hp: 1,
        damage: 1,

      },
      4: {
        id: 4,
        x: 550,
        y: 0,
        radius: 20,
        color: 'green',
        speed: 4,
        hp: 1,
        damage: 1,

      },
    },
  },
  wave7: {
    waveName: 'A Formation',
    waveEnemies: {
      0: {
        id: 0,
        x: 100,
        y: -300,
        radius: 60,
        color: 'green',
        speed: 3,
        hp: 2,
        damage: 4,

      },
      1: {
        id: 1,
        x: 200,
        y: -270,
        radius: 60,
        color: 'green',
        speed: 3,
        hp: 2,
        damage: 4,


      },
      2: {
        id: 2,
        x: 300,
        y: -250,
        radius: 60,
        color: 'green',
        speed: 3,
        hp: 2,
        damage: 4,

      },
      3: {
        id: 3,
        x: 400,
        y: -270,
        radius: 60,
        color: 'green',
        speed: 3,
        hp: 2,
        damage: 4,

      },
      4: {
        id: 4,
        x: 500,
        y: -300,
        radius: 60,
        color: 'green',
        speed: 3,
        hp: 2,
        damage: 4,

      },
    },
  },
  wave8: {
    waveName: 'Armored Column',
    waveEnemies: {
      0: {
        id: 0,
        x: 300,
        y: 0,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      1: {
        id: 1,
        x: 300,
        y: -60,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      2: {
        id: 2,
        x: 300,
        y: -120,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      3: {
        id: 3,
        x: 300,
        y: -180,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      4: {
        id: 4,
        x: 300,
        y: -240,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      5: {
        id: 5,
        x: 300,
        y: -300,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      6: {
        id: 6,
        x: 300,
        y: -360,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
      7: {
        id: 7,
        x: 300,
        y: -420,
        radius: 50,
        color: 'green',
        speed: 1,
        hp: 5,
        damage: 5,

      },
    },
  },
  wave9: {
    waveName: 'Bombers',
    waveEnemies: {
      0: {
        id: 0,
        x: 100,
        y: 0,
        radius: 10,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 10,

      },
      1: {
        id: 1,
        x: 300,
        y: 0,
        radius: 10,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 10,


      },
      2: {
        id: 2,
        x: 500,
        y: 0,
        radius: 10,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 10,

      },
    },
  },
  wave10: {
    waveName: 'Blitzkrieg',
    waveEnemies: {
      0: {
        id: 0,
        x: 200,
        y: 0,
        radius: 45,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      1: {
        id: 1,
        x: 250,
        y: 0,
        radius: 45,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,


      },
      2: {
        id: 2,
        x: 300,
        y: 0,
        radius: 45,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 1,

      },
      3: {
        id: 3,
        x: 100,
        y: 0,
        radius: 10,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 10,

      },
      4: {
        id: 4,
        x: 300,
        y: 0,
        radius: 10,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 10,


      },
      5: {
        id: 5,
        x: 500,
        y: 0,
        radius: 10,
        color: 'green',
        speed: 2,
        hp: 1,
        damage: 10,

      },
    },
  },
  waveEND: {
    waveName: 'GAME OVER',
    waveEnemies: {
      0: {
        id: 0,
        x: 50,
        y: -1000,
        radius: 30,
        color: 'green',
        speed: 0,
        hp: 100000000000,
        damage: 1,

      },
    },
  },
});
module.exports = {
  waves,
};
